worker_processes auto;

events {
    worker_connections 1024;
}

http {
    upstream backend_api {
        server api:7001;
    }

    upstream frontend_ui {
        server frontend:3000;
    }

    server {
        listen 80;

        location /api/ {
            proxy_pass http://backend_api/api/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }

        location /docs/ {
            proxy_pass http://backend_api/docs/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        location /openapi.json {
            proxy_pass http://backend_api/openapi.json;
        }

        location /system/health {
            proxy_pass http://backend_api/health;
        }

        location /uploads/ {
            proxy_pass http://backend_api/uploads/;
        }

        location / {
            proxy_pass http://frontend_ui;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }
    }
}
